spring:
  application:
    name: dscatalog
  profiles:
    active: test
  jpa:
    open-in-view: false
    
security:
  oauth2:
    client:
      client-id: ${CLIENT_ID:dscatalog}
      client-secret: ${CLIENT_SECRET:dscatalog123}

jwt:
  duration: ${JWT_DURATION:86400}